### ISSUE TITLE
[BUG] Segfault when focus is changed

### ISSUE THREAD

**Issue by dabaldassi** [Klevh/SANDAL2#15]
Since I pulled the new version of SANDAL2 there is a segfault when I changed from my game to another window (my shell for example)

**Comment by Klevh** [comment]
I do not manage to reproduce this issue, can you share a code that does it please ?

**Comment by dabaldassi** [comment]
My segfault is fixed but now i can't change the focus.
```cpp
initIteratorWindow();  
 while(getDataWindow((void **)&data) && !nextWindow());
```

I get the focus back when i do this

**Comment by Klevh** [comment]
Now the update is done. There is a system of ID for windows. The `createWindow` now return 0 on failure and the window ID on success. You modify the current user selection (selected using iterators) which can be different from the currently displayed. You can set the currently displayed using `setDisplayWindow` and the window ID, which you can get using `getIDCurrentWindow`. You can get the ID of the currently displayed one using `getIDWindow`.
