### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by ChariereFiedler** [Klevh/SANDAL2#18]
The current Make process does not take into consideration the prerequisites such as:
- SDL2
- Doxygen
- Coverage tools
...

A CMakeLists would improve the way to find the requirements, to define easier more steps and to split among several targets the UT, E2E tests, Coverages... 

Moreover, that will be a nice advance for the Continuous Integration.

**Comment by Klevh** [comment]
It is a good idea ! I am currently working on it.
I have a working CMakeLists to build and install the library AND a working Findsandal2.cmake but, for now, building tests with a CMake does not work.

**Comment by Klevh** [comment]
Done ! 
I also added a "Findsandal2.cmake" in downloadable
