### ISSUE TITLE
Add Action library to quickly interact with elements

### ISSUE THREAD

**Issue by CyrillePierre** [Klevh/SANDAL2#19]
It should be interesting to add some prebuild actions to speed up the manipulation of elements.

## Change the action prototype
Actually, the `action` attribute of `EventElement` has the following prototype:
```c
void (*action)(struct Element*);
```
I think it should be important to include a second parameter `dt` corresponding to the ellapsed time since the last call of this function:
```c
int (*action)(struct Element*, float);
```
The return type `int` indicates the action is finished when the function return `TRUE`.

## The action library
In some game engines, there are functions (or class) which allows to handle the element characteristics like position, scale, rotation, ... in a short instruction. I add links here to the [cocos2d-x action documentation](https://docs.cocos2d-x.org/cocos2d-x/en/actions/) and th [libGDX action documentation](https://github.com/libgdx/libgdx/wiki/Scene2d#actions).

Here is an example. If I want to move my element by 200 pixels to the right during 1 seconds then scale it by 2 during .5 seconds and make a 360° rotation during .5 seconds, I should write something like:
```c
setActionElement(actionSequence(
    actionMoveBy(100, 0, 1), /* (x, y, time) */
    actionScaleBy(1, .5),  /* (scaleXY, time) */
    actionRotateBy(360, .5), /* (angle, time) */
    NULL
));
```
The `NULL` parameter is only used to simplify parsing the variadic function `actionSequence(...)`. Obviously, the syntax of this example can be improved but I think the idea is clear.

Here is a list of actions frequently used on other game engines:

action | description
-------- | ---------------
moveBy / moveTo | Move an element (by a 2D vector / to a specific position)
scaleBy / scaleTo | Scale an element by/to a scalar or a 2D vector
rotateBy / rotateTo | Rotate an element by/to an angle
fadeIn / fadeOut | Gradually change the opacity from 0 to 1 (or inversely)
sequence | Execute a set of actions one after the other
parallel | Execute a set of actions simultaneously

To go further, it is also possible to define the interpolation method. For example, it allows to avoid the boring linear movement of an element and make a funky elastic appearance! I put here a plot of the interpolation functions used in cocos2d-x:
![ease functions of cocos2d-x](https://docs.cocos2d-x.org/cocos2d-x/en/actions/actions-img/easing-functions.png)

**Comment by Klevh** [comment]
For the first one, I am not sure if I will do it as the second one do this job.
I am thinking of doing it with two ways to generate actions.
* First:
```c
Action * a = initAction(action, timing);
a = addFollowingAction(a, initAction(action, timing)); // if it succeed, a == the second parameter, else a is NULL
// and so on
```
* Second:
```c
Action * a = generateAction(
    action, timing,
    action, timing,
    // ...
    NULL);
```
What do you think about it ?

(of course, I will do some generic behaviors such as rotate, translate, scale)

**Comment by Klevh** [comment]
Of course, those actions would be bound to an element and executed when on the element display code. Also, parallel actions would be possible simply by binding a list of actions to an element instead of just one

**Comment by CyrillePierre** [comment]
I think that parallel actions is required because it is possible to put it in a sequence. For example:
```
sequence(A, B, parallel(C, D), E)
```
Without this type of action, it is difficult to have the expected result.

Concerning your two ways to generate actions, I prefer the second. The first is too verbose.

**Comment by Klevh** [comment]
Indeed, I will add this behavior, nice idea
Thanks

**Comment by Klevh** [comment]
I am doing the documentation of the functionnaity, but it worked like that:
```c
setActionListElement(
    e,
    generateParallelAction(
        generateChainedAction(
            actionAsList(setDataAction(initAction(translateW, data1[0]), data1)),
            actionAsList(setDataAction(initAction(translateW, data2[0]), data2)),
            NULL
        ),
        generateChainedAction(
            actionAsList(setDataAction(initAction(translateH, data1[0]), data1)),
            actionAsList(setDataAction(initAction(translateH, data2[0]), data2)),
            NULL
        ),
        NULL
    )
);
```
With data1 and data2 two arrays built like that
`{time in seconds, starting value, ending value}`
data1 has starting value of the element's width (which is the same as its height) and 100 as its ending value. It is the oposite for data2.
The ending result: a block that reduce its width and height then go back to normal.
I will try to bind another issue to this one to close this one and have the other one as the "make pre made actions"

**Comment by Klevh** [comment]
The transalteH and translateW functions takes three arguments when called:
* The element on which they are applied
* A `void *` set of data (`NULL` if by default) bound to the action
* the total time elapsed since the beginning of the action

**Comment by Klevh** [comment]
c160bb3
